version: '3.8'
services:  
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["server", "/data", "--console-address", ":9001"]    
    networks:
      - aws-proxy  

volumes:  
  minio-data:
    driver: local

networks:
  aws-proxy:
    driver: bridge
